#Slicing


In [1]:
a = "Hello, World!"
print(a[1])

e


In [ ]:
a = "Hello, World!"
print(len(a))

13


In [ ]:
b = "Hello, World!"
print(b[:5])

Hello


In [ ]:
b = "Hello, World!"
print(b[2:])

llo, World!


In [ ]:
b = "Hello, World!"
print(b[2:5])

llo


In [ ]:
b = "Hello, World!" #negative slicing
print(b[-5:-2])

orl


#Numpy
https://numpy.org/doc/stable/user/index.html

In [ ]:
import numpy as np

# Creating a NumPy array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

In [ ]:
# Displaying the array
print("Original Array:\n", arr)


Original Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
# Array Slicing Examples

# 1. Slicing a specific portion of the array
# Extracting a subarray from rows 1 to 3 and columns 1 to 3
sub_array = arr[1:3, 1:3]
print("\nSliced Sub-array (Rows 1 to 3, Columns 1 to 3):\n", sub_array)


Sliced Sub-array (Rows 1 to 3, Columns 1 to 3):
 [[ 6  7]
 [10 11]]


In [ ]:
# 2. Slicing rows
# Extracting all rows but only columns from index 2 onwards
slice_rows = arr[:, 2:]
print("\nSlicing all rows but only columns from index 2 onwards:\n", slice_rows)


Slicing all rows but only columns from index 2 onwards:
 [[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]


In [ ]:
# 3. Slicing columns
# Extracting the first two rows of all columns
slice_columns = arr[:2, :]
print("\nSlicing first two rows of all columns:\n", slice_columns)


Slicing first two rows of all columns:
 [[1 2 3 4]
 [5 6 7 8]]


In [ ]:
# 4. Negative Indexing
# Extracting the last two rows and the last two columns
neg_index_slice = arr[-2:, -2:]
print("\nSlicing last two rows and last two columns:\n", neg_index_slice)


Slicing last two rows and last two columns:
 [[11 12]
 [15 16]]


In [ ]:
# 5. Step Slicing
# Extracting elements with step slicing (every second element from rows and columns)
step_slice = arr[::2, ::2]
print("\nSlicing every second element from rows and columns:\n", step_slice)


Slicing every second element from rows and columns:
 [[ 1  3]
 [ 9 11]]


In [ ]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

sub_arr = arr[[1, 3], [1, 2]]

print(sub_arr)




[ 6 15]


In [ ]:
import pandas as pd



In [ ]:
df = pd.read_csv('/content/null_values.csv')

In [ ]:
df


Name   Age  Height  Weight  result  study.h
0   John  28.0   170.0    70.0    3.50      6.0
1   Anna   NaN   165.0     NaN    4.00      8.0
2   Mark  35.0     NaN    80.0    3.20      4.0
3   Lucy  24.0   160.0    55.0    2.75      NaN
4  Peter   NaN     NaN     NaN     NaN      NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Name     5 non-null      object 
 1   Age      3 non-null      float64
 2   Height   3 non-null      float64
 3   Weight   3 non-null      float64
 4   result   4 non-null      float64
 5   study.h  3 non-null      float64
dtypes: float64(5), object(1)
memory usage: 368.0+ bytes


In [ ]:
df.shape

(5, 6)

In [ ]:
df.isnull().sum()

Name       0
Age        2
Height     2
Weight     2
result     1
study.h    2
dtype: int64

In [ ]:
len(df)

5

In [ ]:
df.isnull().sum() / len(df)* 100

Name        0.0
Age        40.0
Height     40.0
Weight     40.0
result     20.0
study.h    40.0
dtype: float64

  #Null handeling


In [ ]:
df_drop = df.dropna()
df_drop

Name   Age  Height  Weight  result  study.h
0  John  28.0   170.0    70.0     3.5      6.0

In [ ]:
df = df.drop(['Name'],axis=1)

In [ ]:
df

Age  Height  Weight  result  study.h
0  28.0   170.0    70.0    3.50      6.0
1   NaN   165.0     NaN    4.00      8.0
2  35.0     NaN    80.0    3.20      4.0
3  24.0   160.0    55.0    2.75      NaN
4   NaN     NaN     NaN     NaN      NaN

In [ ]:
df1 = df.fillna(df.mean())

In [ ]:
df1

Age  Height     Weight  result  study.h
0  28.0   170.0  70.000000  3.5000      6.0
1  29.0   165.0  68.333333  4.0000      8.0
2  35.0   165.0  80.000000  3.2000      4.0
3  24.0   160.0  55.000000  2.7500      6.0
4  29.0   165.0  68.333333  3.3625      6.0

In [ ]:
# Fill NaN values with a specific value (e.g., 0)
df_fillna_zero = df1.fillna(0)

In [ ]:
df_fillna_zero

Age  Height     Weight  result  study.h
0  28.0   170.0  70.000000  3.5000      6.0
1  29.0   165.0  68.333333  4.0000      8.0
2  35.0   165.0  80.000000  3.2000      4.0
3  24.0   160.0  55.000000  2.7500      6.0
4  29.0   165.0  68.333333  3.3625      6.0

In [ ]:
# Fill NaN values with the previous value in the column (forward fill)
df_fillna_ffill = df.fillna(method='ffill')

<ipython-input-159-4282233ab9b9>:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_fillna_ffill = df.fillna(method='ffill')


In [ ]:
df_fillna_ffill

Age  Height  Weight  result  study.h
0  28.0   170.0    70.0    3.50      6.0
1  28.0   165.0    70.0    4.00      8.0
2  35.0   165.0    80.0    3.20      4.0
3  24.0   160.0    55.0    2.75      4.0
4  24.0   160.0    55.0    2.75      4.0

In [ ]:
# Fill NaN values with the next value in the column (backward fill)
df_fillna_bfill = df.fillna(method='bfill')

<ipython-input-161-1e1f80fccd6c>:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_fillna_bfill = df.fillna(method='bfill')


In [ ]:
df_fillna_bfill

Age  Height  Weight  result  study.h
0  28.0   170.0    70.0    3.50      6.0
1  35.0   165.0    80.0    4.00      8.0
2  35.0   160.0    80.0    3.20      4.0
3  24.0   160.0    55.0    2.75      NaN
4   NaN     NaN     NaN     NaN      NaN

In [ ]:
df

sepal_length  sepal_width  petal_length
0             5.1          3.5           1.4
1             4.9          3.0           1.4
2             4.7          3.2           1.3
3             4.6          3.1           1.5
4             5.0          3.6           1.4
..            ...          ...           ...
145           6.7          3.0           5.2
146           6.3          2.5           5.0
147           6.5          3.0           5.2
148           6.2          3.4           5.4
149           5.9          3.0           5.1

[150 rows x 3 columns]

In [ ]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length'], dtype='object')

In [ ]:
df.values

array([[5.1, 3.5, 1.4],
       [4.9, 3. , 1.4],
       [4.7, 3.2, 1.3],
       [4.6, 3.1, 1.5],
       [5. , 3.6, 1.4],
       [5.4, 3.9, 1.7],
       [4.6, 3.4, 1.4],
       [5. , 3.4, 1.5],
       [4.4, 2.9, 1.4],
       [4.9, 3.1, 1.5],
       [5.4, 3.7, 1.5],
       [4.8, 3.4, 1.6],
       [4.8, 3. , 1.4],
       [4.3, 3. , 1.1],
       [5.8, 4. , 1.2],
       [5.7, 4.4, 1.5],
       [5.4, 3.9, 1.3],
       [5.1, 3.5, 1.4],
       [5.7, 3.8, 1.7],
       [5.1, 3.8, 1.5],
       [5.4, 3.4, 1.7],
       [5.1, 3.7, 1.5],
       [4.6, 3.6, 1. ],
       [5.1, 3.3, 1.7],
       [4.8, 3.4, 1.9],
       [5. , 3. , 1.6],
       [5. , 3.4, 1.6],
       [5.2, 3.5, 1.5],
       [5.2, 3.4, 1.4],
       [4.7, 3.2, 1.6],
       [4.8, 3.1, 1.6],
       [5.4, 3.4, 1.5],
       [5.2, 4.1, 1.5],
       [5.5, 4.2, 1.4],
       [4.9, 3.1, 1.5],
       [5. , 3.2, 1.2],
       [5.5, 3.5, 1.3],
       [4.9, 3.1, 1.5],
       [4.4, 3. , 1.3],
       [5.1, 3.4, 1.5],
       [5. , 3.5, 1.3],
       [4.5, 2.3

In [ ]:
df.sort_values("sepal_length",ascending=True)

In [ ]:
df = df.drop(['species'],axis=1)

In [ ]:
df.describe()


sepal_length  sepal_width  petal_length
count    150.000000   150.000000    150.000000
mean       5.843333     3.054000      3.758667
std        0.828066     0.433594      1.764420
min        4.300000     2.000000      1.000000
25%        5.100000     2.800000      1.600000
50%        5.800000     3.000000      4.350000
75%        6.400000     3.300000      5.100000
max        7.900000     4.400000      6.900000

In [ ]:
df.corr()

sepal_length  sepal_width  petal_length
sepal_length      1.000000    -0.109369      0.871754
sepal_width      -0.109369     1.000000     -0.420516
petal_length      0.871754    -0.420516      1.000000

In [ ]:
import seaborn as sns
sns.heatmap(df.corr(),annot=True)